/*
 * bignum_fuzz_test.c — property-based regression for kernel/bignum.c's modular
 * reduction, checked against Python's arbitrary-precision integers (an
 * independent implementation, not anything derived from this codebase).
 *
 * bn_mod is `static` (internal to bignum.c) and was previously validated only
 * indirectly, through ECDSA/RSA known-answer signature checks (crypto_test.c)
 * -- those exercise it at exactly two bit-widths (P-384, RSA-2048) and only on
 * inputs that happen to come from a valid signature. This #includes the real
 * bignum.c (like tests/url/url_test.c does for url.c) to reach bn_mod directly
 * and run it over thousands of vectors spanning the whole supported range
 * (1..8320 bits) generated by gen_bignum_vectors.py. This is the correctness
 * net a reduction-algorithm rewrite (bit-serial -> word-at-a-time) needs to be
 * verified against before it ever touches signature-verification code: a bug
 * here is a security bug (a certificate could wrongly verify), not a visual
 * glitch. Build under ASan+UBSan via tests/run-bignum-fuzz-tests.sh.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "../../kernel/bignum.c"

static int hexval(char c) {
    if (c >= '0' && c <= '9') return c - '0';
    return (c | 32) - 'a' + 10;
}

static void bn_from_hex(bignum *b, const char *hex) {
    uint8_t buf[BN_LIMBS * 4];
    size_t len = strlen(hex) / 2;
    for (size_t i = 0; i < len; i++)
        buf[i] = (uint8_t)((hexval(hex[2 * i]) << 4) | hexval(hex[2 * i + 1]));
    bn_from_bytes(b, buf, len);
}

int main(int argc, char **argv) {
    if (argc != 2) { fprintf(stderr, "usage: %s <vectors-file>\n", argv[0]); return 1; }
    FILE *f = fopen(argv[1], "r");
    if (!f) { perror("fopen"); return 1; }

    char la[2100], lm[2100], le[2100];
    int total = 0, fails = 0;
    while (fscanf(f, "%2099s %2099s %2099s", la, lm, le) == 3) {
        bignum a, m, want, got;
        bn_from_hex(&a, la);
        bn_from_hex(&m, lm);
        bn_from_hex(&want, le);
        bn_mod(&got, &a, &m);
        total++;
        if (bn_cmp(&got, &want) != 0) {
            fails++;
            if (fails <= 10)
                fprintf(stderr, "  FAIL: a=%s m=%s -> mismatch (expected %s)\n", la, lm, le);
        }
    }
    fclose(f);

    if (total == 0) { fprintf(stderr, "FAIL: no vectors read from %s\n", argv[1]); return 1; }
    if (fails) { printf("FAIL: %d/%d bn_mod fuzz vectors mismatched\n", fails, total); return 1; }
    printf("PASS: bn_mod matches the Python arbitrary-precision oracle on all %d vectors (1..%d-bit)\n",
           total, BN_LIMBS * 32);
    return 0;
}
