// fantest.c — userspace file materialization (fanotify pre-content, M1128). The
// child becomes the /fan daemon; the parent reads /fan/greeting, which has no
// backing store — the kernel parks the read and asks the daemon, which generates
// the bytes on the fly and hands them back. A userspace filesystem: files that
// don't exist until someone asks for them.
#include "ulib.h"

int main(void) {
    long pid = sys_fork();
    if (pid == 0) {
        // ---- child: the /fan daemon ----
        sys_fanotify_serve();
        char name[80];
        long n = sys_fanotify_wait(name, sizeof name - 1);   // block until a read request
        if (n > 0) {
            name[n] = 0;
            char out[160]; int c = 0;
            const char *pre = "materialized-on-demand: ";
            for (int i = 0; pre[i]; i++) out[c++] = pre[i];
            for (int i = 0; name[i]; i++) out[c++] = name[i];
            sys_fanotify_provide(out, c);                    // hand the bytes to the reader
        }
        sys_sleep(20000);
        sys_exit(0);
    }

    // ---- parent: the reader ----
    sys_sleep(800);                                          // let the daemon register
    char buf[160];
    long n = sys_readfile("/fan/greeting", buf, sizeof buf - 1);
    if (n > 0) { buf[n] = 0; print("reader: read /fan/greeting (no backing file) -> \""); print(buf); print("\"\n"); }
    else        print("reader: /fan/greeting read failed\n");
    print("reader: that content was generated by the userspace daemon on first access.\n");
    int st; sys_waitpid((int)pid, &st);   /* was a bare sys_sleep(20000): the daemon child was never reaped, unlike the identical fork-a-helper pattern in uffdtest.c. Waiting on it keeps the window up for about as long as before (the daemon's own sleep(20000) still runs), but now properly reaps it. */
    return 0;
}
