/*
 * lights.c — Lights Out.
 *
 * A 5x5 grid of lights. Pressing a cell toggles it and its four orthogonal
 * neighbours. Turn every light off to win. The starting board is generated by
 * applying random presses to an all-off grid, so it is always solvable. Tracks
 * how many presses you take.
 *
 * Arrows move the cursor, Space toggles, n new board, q quit.
 */
#include "ulib.h"

#define N 5
static int g[N][N];                 /* 1 = lit */
static int cr, cc, moves, won;

static unsigned rng;
static unsigned rnd(void) { rng ^= rng << 13; rng ^= rng >> 17; rng ^= rng << 5; return rng; }

static void toggle(int r, int c) {
    static const int dr[5] = { 0,-1, 1, 0, 0 }, dc[5] = { 0, 0, 0,-1, 1 };
    for (int i = 0; i < 5; i++) {
        int rr = r + dr[i], cc2 = c + dc[i];
        if (rr >= 0 && rr < N && cc2 >= 0 && cc2 < N) g[rr][cc2] ^= 1;
    }
}

static int lit_count(void) {
    int n = 0;
    for (int r = 0; r < N; r++) for (int c = 0; c < N; c++) n += g[r][c];
    return n;
}

static void putn(int n) {
    char t[8]; int i = 0;
    if (n == 0) { print("0"); return; }
    while (n) { t[i++] = (char)('0' + n % 10); n /= 10; }
    char s[8]; int j = 0; while (i) s[j++] = t[--i]; s[j] = 0; print(s);
}

static void newboard(void) {
    for (int r = 0; r < N; r++) for (int c = 0; c < N; c++) g[r][c] = 0;
    int presses = 4 + (int)(rnd() % 6);                 /* solvable by construction */
    while (presses--) toggle((int)(rnd() % N), (int)(rnd() % N));
    if (lit_count() == 0) toggle((int)(rnd() % N), (int)(rnd() % N));   /* never start solved */
    cr = cc = 0; moves = 0; won = 0;
}

static void render(void) {
    sys_clear();
    sys_setcolor(4); print("\n  Lights Out"); sys_setcolor(0);
    print("     lit="); putn(lit_count());
    print("  moves="); putn(moves); print("\n\n");
    for (int r = 0; r < N; r++) {
        print("    ");
        for (int c = 0; c < N; c++) {
            int cur = (r == cr && c == cc);
            sys_setcolor(g[r][c] ? 14 : 8);             /* lit = bright yellow, off = grey */
            char cell[5];
            cell[0] = cur ? '[' : ' ';
            cell[1] = g[r][c] ? '#' : '.';
            cell[2] = g[r][c] ? '#' : '.';
            cell[3] = cur ? ']' : ' ';
            cell[4] = 0;
            print(cell);
        }
        sys_setcolor(0); print("\n");
    }
    print("\n  ");
    if (won) { sys_setcolor(10); print("Solved in "); putn(moves); print(" moves!  (n = new)"); sys_setcolor(0); }
    else print("arrows move  space toggle");
    print("\n  n new board   q quit\n");
}

int main(void) {
    rng = (unsigned)sys_uptime_ms() | 1u;
    newboard();
    render();
    for (;;) {
        int k = sys_pollkey();
        if (k < 0) { sys_sleep(20); continue; }
        if (k == 'q' || k == 'Q') break;
        if (k == 'n' || k == 'N') { newboard(); render(); continue; }
        if (won) continue;
        if      (k == 0x11) { if (cr > 0) cr--; render(); }
        else if (k == 0x12) { if (cr < N - 1) cr++; render(); }
        else if (k == 0x13) { if (cc > 0) cc--; render(); }
        else if (k == 0x14) { if (cc < N - 1) cc++; render(); }
        else if (k == ' ' || k == '\n' || k == '\r') {
            toggle(cr, cc); moves++;
            if (lit_count() == 0) { won = 1; sys_beep(880, 120); sys_beep(1320, 120); }
            render();
        }
    }
    return 0;
}
